spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  datasource:
    username: root
    password: '{cipher}ec4ef20e459a989490f3a5c879896bf905c6a197a7a7c99a7025922e2a35caa5'
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: never
  zipkin:
    base-url: http://localhost:1234
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0
logging:
  level:
    root: debug
    org:
      hibernate:
        type: trace
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka