hystrix:
    command:
        default:
            circuitBreaker:
                errorThresholdPercentage: 50
                requestVolumeThreshold: 4
                sleepWindowInMilliseconds: 60000
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
            metrics:
                rollingStats:
                    timeInMilliseconds: 10000
spring:
    jackson:
        default-property-inclusion: NON_NULL